services:
  - type: web
    name: real-estate-backend
    env: node
    rootDir: backend
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString

databases:
  - name: real-estate-db
    databaseName: realestate
    user: realestate
    plan: free
    region: frankfurt
